// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace CppWinRTWinUI3ListView
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
       
    }
}
